version: "3"

services:
  postgres:
    image: postgres
    container_name: java-postgres
    env_file:
      - ./src/main/resources/static/env_vars.env
    volumes:
      - ./src/main/resources/static/sql/sqlScript.sql:/docker-entrypoint-initdb.d/sqlScript.sql
    ports:
      - "5432:5432"
  app:
    build: ./
    container_name: java-app
    ports:
      - "8080:8080"
