CREATE TABLE person (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName VARCHAR(200) NOT NULL UNIQUE ,
    birthYear INT NOT NULL
);

CREATE TABLE book(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    personId INT REFERENCES person(id) ON DELETE SET NULL
);

INSERT INTO person (fullName, birthYear) VALUES
    ('Иванов Иван Иванович', 1990),
    ('Петров Петр Петрович', 1985),
    ('Сидоров Сидор Сидорович', 1995),
    ('Козлова Екатерина Ивановна', 1982),
    ('Смирнова Ольга Петровна', 1998);

INSERT INTO book (name, author, year, personId) VALUES
    ('Война и мир', 'Лев Толстой', 1869, 1),
    ('Преступление и наказание', 'Фёдор Достоевский', 1866, 2),
    ('Евгений Онегин', 'Александр Пушкин', 1833, 3),
    ('Мастер и Маргарита', 'Михаил Булгаков', 1967, 4),
    ('Анна Каренина', 'Лев Толстой', 1877, 5),
    ('Двенадцать стульев', 'Илья Ильф и Евгений Петров', 1928, NULL),
    ('Маленький принц', 'Антуан де Сент-Экзюпери', 1943, NULL),
    ('Горе от ума', 'Александр Грибоедов', 1825, NULL),
    ('Мёртвые души', 'Николай Гоголь', 1842, NULL),
    ('Тихий Дон', 'Михаил Шолохов', 1928, NULL);
