CREATE TABLE person
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName      VARCHAR(200) NOT NULL UNIQUE,
    password      VARCHAR NOT NULL,
    date_of_birth DATE         NOT NULL,
    role          VARCHAR NOT NULL,
    status        VARCHAR(6) NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_who VARCHAR(100) NOT NULL
);

CREATE TABLE book
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(200) NOT NULL,
    author   VARCHAR(100) NOT NULL,
    year     INT          NOT NULL,
    personId INT          REFERENCES person (id) ON DELETE SET NULL,
    issued   TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_who VARCHAR(100) NOT NULL
);